# ----------<pyinstaller 설정 파일>----------

# 메인 파일 이름
main_file = 'HEVIMetalBoxer.py'

# 데이타 파일들
data_files = [
    # 폰트
    'FONT_KOTRA_HOPE_TTF.ttf'
]

# 데이타가 들어있는 폴더들
data_folders = [
    'resource_image', # 이미지들이 저장된 폴더
    'resource_sound'  # 사운드들이 저장된 폴더
]
